name: build-docs-actions
run-name: ${{ github.actor }} is publishing docs
on:
  push:
    branches:
      - main
      - 'pyarmor/docs/**'

# jobs:
#   test-no-disk:
#     runs-on: ubuntu-latest
#     steps:
#       - run: sudo mv /dev/disk /dev/notdisk
#       - run: pip install pyarmor
#       - run: pyarmor -h

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install graphviz and sphinx
        run: |
            sudo apt install graphviz
            pip install sphinx
            pip install sphinx-rtd-theme
            pip install linuxdoc
      - name: Build static files
        id: build
        run: |
            make html
        working-directory: ./pyarmor/docs/zh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pyarmor/docs/zh/_build/html/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
