name: test-github-actions
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  test-no-disk:
    runs-on: ubuntu-latest
    steps:
      - run: sudo mv /dev/disk /dev/notdisk
      - run: pip install pyarmor
      - run: pyarmor -h
