name: pyarmor-smoke-test
run-name: ${{ github.actor }} is testing Pyarmor
on:
  push
  # create

jobs:
  test-free-threading:
    runs-on: ubuntu-latest
    steps:
      - run: sudo add-apt-repository ppa:deadsnakes
      - run: sudo apt-get update
      - run: sudo apt-get install python3.13-nogil
      - run: wget https://pyarmor.dashingsoft.com/downloads/temp/pyarmor_mini.tar.gz
      - run: tar xzf pyarmor_mini.tar.gz
      - run: cp -a linux.x86_64/libs/cp3.13t/pyarmor_minit.so pyarmor_mini.so
      - run: python3.13t -c "import pyarmor_mini"
  #     - run: wget https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-smoke-test.tar.gz
  #     - run: tar xzf pyarmor-smoke-test.tar.gz
  #     - run: pip install test/pyarmor.cli.core.tar.gz
  #     - run: pip install test/pyarmor.cli.tar.gz
  #     - run: pip install test/pyarmor.mini.tar.gz
  #     - run: pyarmor init test/foo.py
  #     - run: pyarmor build --mini
  #     - run: python3 dist/foo.py
  test-free-threading-macos:
    runs-on: macos-13
    steps:
      - run: brew install python-freethreading
      - run: curl -O https://pyarmor.dashingsoft.com/downloads/temp/pyarmor_mini.tar.gz
      - run: tar xzf pyarmor_mini.tar.gz
      - run: cp -a darwin.x86_64/libs/cp3.13t/pyarmor_minit.so pyarmor_mini.so
      - run: $(brew --prefix)/bin/python3.13t -c "import pyarmor_mini"
