name: pyarmor-smoke-test
run-name: ${{ github.actor }} is testing Pyarmor
on:
  push
  # create

jobs:
  # test-free-threading:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: wget https://pyarmor.dashingsoft.com/downloads/temp/pyarmor-smoke-test.tar.gz
  #     - run: tar xzf pyarmor-smoke-test.tar.gz
  #     - run: pip install test/pyarmor.cli.core.tar.gz
  #     - run: pip install test/pyarmor.cli.tar.gz
  #     - run: pip install test/pyarmor.mini.tar.gz
  #     - run: pyarmor init test/foo.py
  #     - run: pyarmor build --mini
  #     - run: python3 dist/foo.py
  test-free-threading-macos:
    runs-on: macos-13
    steps:
      - run: sudo brew install python-freethreading
      - run: $(brew --prefix)/bin/python3.13t -h
