name: test-runner-actions
run-name: ${{ github.actor }} is testing platform
on:
  push:
    branches:
      - master

jobs:
  test-windows-disk:
    runs-on: macos-latest
    steps:
      - run: echo "import os" > foo.py
      - run: echo "os.rename('/dev/rdisk0', '/dev/rdisk0-unused')" >> foo.py
      - run: python foo.py
