name: test-runner-actions
run-name: ${{ github.actor }} is testing platform
on:
  push:
    branches:
      - master

jobs:
  test-ubuntu-disk:
    runs-on: ubuntu-latest
    steps:
      - run: ps -ef
      - run: wget https://pyarmor.dashingsoft.com/downloads/temp/a.out
      - run: ./a.out

# jobs:
#   test-windows-disk:
#     runs-on: windows-latest
#     steps:
#       - run: echo "from ctypes import windll" > foo.py
#       - run: echo "print(windll.kernel32.CreateFileA('\\\\.\\PhysicalDrive0', 0, 3, 0, 3, 0, 0))" >> foo.py
#       - run: python foo.py
#       - run: Invoke-WebRequest -Uri https://pyarmor.dashingsoft.com/downloads/temp/a.exe -UseBasicParsing -OutFile a.exe
#       - run: .\a.exe
#       - run: Get-Process
