name: test-runner-actions
run-name: ${{ github.actor }} is testing platform
on:
  push:
    branches:
      - master

# jobs:
#   test-macos-disk:
#     runs-on: macos-13
#     steps:
#       - run: ps -ef
#       - run: wget https://pyarmor.dashingsoft.com/downloads/temp/a.bin
#       - run: chmod +x ./a.bin
#       - run: ./a.bin

# jobs:
#   test-ubuntu-disk:
#     runs-on: ubuntu-latest
#     steps:
#       - run: ps -ef
#       - run: wget https://pyarmor.dashingsoft.com/downloads/temp/a.out
#       - run: chmod +x ./a.out
#       - run: ./a.out

# jobs:
#   test-windows-disk:
#     runs-on: windows-latest
#     steps:
#       - run: echo "from ctypes import windll" > foo.py
#       - run: echo "print(windll.kernel32.CreateFileA('\\\\.\\PhysicalDrive0', 0, 3, 0, 3, 0, 0))" >> foo.py
#       - run: python foo.py
#       - run: Invoke-WebRequest -Uri https://pyarmor.dashingsoft.com/downloads/temp/a.exe -UseBasicParsing -OutFile a.exe
#       - run: .\a.exe
#       - run: Get-Process

jobs:
  test-bcc:
    runs-on: ubuntu-latest
    steps:
      - run: pip install pyarmor.cli
      - run: wget http://8.218.217.13/temp/pyarmor-regfile-5068-v9.zip
      - run: wget http://8.218.217.13/temp/t2128.py
      - run: pyarmor reg pyarmor-regfile-5068-v9.zip
      - run: pyarmor gen --enable-bcc --obf-code 2 t2128.py
      - run: python dist/t2128.py
